#!/usr/bin/python
Import ('env')

sources = env.Glob('*.c')

incs = '. ../blender/blenlib ../blender/makesdna ../blender/bmesh '
incs += '../blender/blenkernel '
incs += '../../intern/guardedalloc ../../intern/rangetree'

env.BlenderLib ( 'bf_unit_test', sources, Split(incs), libtype=['core'], priority=[160] )
